print("Welcome to the band name generator")
name1 = input("What is the name of your city?\n")
name2 = input("What is the name of your pet?\n")
print ( "Your band's name could be: " + name1 + "\'s " + name2)
print("Tah Dah")